// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeOT6HNpdgOZuRcGE0sPBYRcvbUTIVxZI',
    appId: '1:505307546033:web:0f0aa1867c612c71dfbd90',
    messagingSenderId: '505307546033',
    projectId: 'afrilyft-eeb6b',
    authDomain: 'afrilyft-eeb6b.firebaseapp.com',
    storageBucket: 'afrilyft-eeb6b.firebasestorage.app',
    measurementId: 'G-11RLSQJVRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2CYlQeEJvQ93bfUx2lXordr4dwB-Bkc',
    appId: '1:505307546033:android:0eb40872531a5cbcdfbd90',
    messagingSenderId: '505307546033',
    projectId: 'afrilyft-eeb6b',
    storageBucket: 'afrilyft-eeb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOv1xxJNNCKDtrWAcKhtPYaHQbrIm8s44',
    appId: '1:505307546033:ios:87c6dcb62279bab9dfbd90',
    messagingSenderId: '505307546033',
    projectId: 'afrilyft-eeb6b',
    storageBucket: 'afrilyft-eeb6b.firebasestorage.app',
    iosBundleId: 'com.example.afrilyft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOv1xxJNNCKDtrWAcKhtPYaHQbrIm8s44',
    appId: '1:505307546033:ios:87c6dcb62279bab9dfbd90',
    messagingSenderId: '505307546033',
    projectId: 'afrilyft-eeb6b',
    storageBucket: 'afrilyft-eeb6b.firebasestorage.app',
    iosBundleId: 'com.example.afrilyft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeOT6HNpdgOZuRcGE0sPBYRcvbUTIVxZI',
    appId: '1:505307546033:web:a2fb50c7a96c8c35dfbd90',
    messagingSenderId: '505307546033',
    projectId: 'afrilyft-eeb6b',
    authDomain: 'afrilyft-eeb6b.firebaseapp.com',
    storageBucket: 'afrilyft-eeb6b.firebasestorage.app',
    measurementId: 'G-458G17LC1G',
  );
}
